/**
 * POST /api/exercises/:id/duplicate
 * Duplicate an exercise with a unique slug
 *
 * Access: Authenticated users only
 */
import { PayloadRequest } from 'payload'
import type { Exercise } from '@/payload-types'

export async function duplicateExercise(req: PayloadRequest) {
  // 1) Auth - endpoints not authenticated by default
  if (!req.user) {
    return Response.json({ error: 'Authentication required' }, { status: 401 })
  }

  // 2) Get exercise ID from route params
  const exerciseId = req.routeParams?.id

  if (!exerciseId) {
    return Response.json({ error: 'Exercise ID is required' }, { status: 400 })
  }

  try {
    // 3) Fetch the original exercise
    const originalExercise = await req.payload.findByID({
      collection: 'exercises',
      id: exerciseId,
      depth: 0,
    })

    if (!originalExercise) {
      return Response.json({ error: 'Exercise not found' }, { status: 404 })
    }

    // 4) Create a deep copy of the exercise data, excluding fields that should not be duplicated
    const {
      id,
      createdAt,
      updatedAt,
      slug, // Will be auto-generated by hook
      ...exerciseData
    } = originalExercise as Exercise

    // 5) Prepare duplicate data
    const duplicateData = {
      ...exerciseData,
      // The generateSlug hook will create a unique slug based on the title
      // Append " (Copy)" to title to make it clear it's a duplicate
      title: `${exerciseData.title} (Copy)`,
    }

    // 6) Create the duplicate exercise
    // The beforeValidate hooks (generateSlug) will automatically:
    // - Generate a unique slug by appending -2, -3, etc. if needed
    // - Ensure slug uniqueness within the lesson
    const duplicatedExercise = await req.payload.create({
      collection: 'exercises',
      // Type assertion needed: duplicateData has all required fields from originalExercise
      // except id/createdAt/updatedAt/slug which are auto-generated or handled by hooks
      data: duplicateData as Omit<Exercise, 'id' | 'createdAt' | 'updatedAt' | 'slug'>,
    })

    return Response.json({
      success: true,
      exercise: duplicatedExercise,
    })
  } catch (error) {
    console.error('[duplicateExercise] Error:', error)

    return Response.json(
      {
        error: 'Failed to duplicate exercise',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 },
    )
  }
}
