/**
 * @fileType plugin
 * @domain inspector
 * @pattern success-tracker-plugin
 * @ai-summary Tracks Cody pipeline success rates and trends, posts daily digest
 *
 * Queries GitHub Actions API for cody.yml workflow runs over 7 and 30 days.
 * Calculates success rate, average duration, and trend direction.
 * Posts digest to Slack and/or the digest issue.
 * Triggers a warning action if the 7-day success rate drops >15pp below 30-day.
 */

import type { InspectorPlugin, ActionRequest, InspectorContext } from '../../../core/types'
import { computeReport } from './metrics'
import { formatSlackMessage, formatMarkdownReport } from './formatter'

const CODY_WORKFLOW = 'cody.yml'
const DEDUP_WINDOW_MINUTES = 23 * 60
const DEGRADATION_DEDUP_MINUTES = 48 * 60 // 48 hours
/** Threshold in percentage points for degradation warning. */
const DEGRADATION_WARNING_PP = -15

/**
 * Success Rate Tracker plugin.
 *
 * Runs ~daily (every 6th cycle + 23h dedup).
 */
export const successTrackerPlugin: InspectorPlugin = {
  name: 'success-tracker',
  description: 'Track Cody pipeline success rate and post daily metrics digest',
  domain: 'cody',
  schedule: { every: 6 },

  async run(ctx): Promise<ActionRequest[]> {
    ctx.log.debug('Running success-tracker plugin')

    // Fetch last 100 completed runs (covers ~30 days at typical cadence)
    const runs = ctx.github.listWorkflowRuns(CODY_WORKFLOW, {
      per_page: 100,
      status: 'completed',
    })

    if (runs.length === 0) {
      ctx.log.info('No completed workflow runs found — skipping success-tracker')
      return []
    }

    const report = computeReport(runs)

    if (!report) {
      ctx.log.info('Insufficient run data for metrics — skipping success-tracker')
      return []
    }

    ctx.log.info(
      {
        sevenDayRate: report.sevenDay.successRate,
        thirtyDayRate: report.thirtyDay.successRate,
        trend: report.trendDirection,
        trendPp: report.trendPp,
      },
      'Computed success metrics',
    )

    const isDegrading = report.trendPp <= DEGRADATION_WARNING_PP
    const urgency = isDegrading ? 'warning' : 'info'

    const actions: ActionRequest[] = []

    // Slack action
    if (ctx.slack?.isConfigured()) {
      actions.push({
        plugin: 'success-tracker',
        type: 'slack-digest',
        urgency,
        title: 'Cody metrics Slack digest',
        detail: formatSlackMessage(report),
        dedupKey: 'success-tracker:slack-daily',
        dedupWindowMinutes: DEDUP_WINDOW_MINUTES,
        async execute(execCtx: InspectorContext): Promise<{ success: boolean; message?: string }> {
          if (!execCtx.slack?.isConfigured()) {
            return { success: false, message: 'Slack not configured at execution time' }
          }
          const msg = formatSlackMessage(report)
          await execCtx.slack.postMessage(msg)
          return { success: true, message: 'Slack digest sent' }
        },
      })
    }

    // Digest issue action
    if (ctx.digestIssue) {
      actions.push({
        plugin: 'success-tracker',
        type: 'digest',
        urgency,
        title: 'Cody metrics digest',
        detail: `7d: ${report.sevenDay.successRate}% | 30d: ${report.thirtyDay.successRate}% | trend: ${report.trendDirection}`,
        dedupKey: 'success-tracker:digest-daily',
        dedupWindowMinutes: DEDUP_WINDOW_MINUTES,
        async execute(execCtx: InspectorContext): Promise<{ success: boolean; message?: string }> {
          if (!execCtx.digestIssue) {
            return { success: false, message: 'Digest issue not configured at execution time' }
          }
          const markdown = formatMarkdownReport(report, execCtx.cycleNumber)
          execCtx.github.postComment(execCtx.digestIssue, markdown)
          return { success: true, message: 'Digest posted' }
        },
      })
    }

    // Degradation investigation action - create a self-healing Cody task
    if (isDegrading) {
      const degradationTitle = `[Cody] Pipeline degradation investigation: ${report.sevenDay.successRate}% (7d) vs ${report.thirtyDay.successRate}% (30d)`
      const degradationBody = `## Pipeline Degradation Detected

The 7-day success rate (${report.sevenDay.successRate}%) has dropped by more than ${Math.abs(report.trendPp)} percentage points below the 30-day rate (${report.thirtyDay.successRate}%).

### Current Metrics

| Period | Success Rate | Runs |
|--------|-------------|------|
| 7 days | ${report.sevenDay.successRate}% | ${report.sevenDay.total} |
| 30 days | ${report.thirtyDay.successRate}% | ${report.thirtyDay.total} |

---

### 🤖 Self-Healing Task

@cody fix

Investigate the recent pipeline degradation. Check the last 5 failed workflow runs for common error patterns. Identify the root cause and implement a fix.

**Priority:** high
**Risk:** low
**Control:** auto

---

_Auto-generated by the Success Tracker inspector plugin_`

      actions.push({
        plugin: 'success-tracker',
        type: 'create-degradation-issue',
        urgency: 'warning',
        title: 'Pipeline degradation investigation',
        detail: `7d: ${report.sevenDay.successRate}% vs 30d: ${report.thirtyDay.successRate}% (${report.trendPp}pp)`,
        dedupKey: 'success-tracker:degradation',
        dedupWindowMinutes: DEGRADATION_DEDUP_MINUTES,
        async execute(execCtx: InspectorContext): Promise<{ success: boolean; message?: string }> {
          // Check for existing open degradation issue
          const existing = execCtx.github.searchIssues(
            `[Cody] Pipeline degradation investigation in:title is:open`,
          )
          if (existing.length > 0) {
            return {
              success: true,
              message: `Degradation issue already exists (#${existing[0].number})`,
            }
          }

          const issueNumber = execCtx.github.createIssue(degradationTitle, degradationBody, [
            'cody:improvement',
            'priority:high',
          ])
          if (issueNumber) {
            return {
              success: true,
              message: `Created degradation investigation issue #${issueNumber}`,
            }
          }
          return { success: false, message: 'Failed to create degradation issue' }
        },
      })
    }

    return actions
  },
}
